### ISSUE TITLE
error installing in windows 10

### ISSUE THREAD

**Issue by hemant1612** [workshopper/levelmeup#112]
This is the log generated when I tried to install levelmeup on windows 10
C:\Users\HP>npm install -g levelmeup
C:\Users\HP\AppData\Roaming\npm\levelmeup -> C:\Users\HP\AppData\Roaming\npm\node_modules\levelmeup\bin\levelmeup

> leveldown@1.6.0 install C:\Users\HP\AppData\Roaming\npm\node_modules\levelmeup\node_modules\leveldown
> prebuild-install || node-gyp rebuild

prebuild-install info begin Prebuild-install version 2.1.2
prebuild-install info looking for local prebuild @ prebuilds\leveldown-v1.6.0-node-v48-win32-x64.tar.gz
prebuild-install info looking for cached prebuild @ C:\Users\HP\AppData\Roaming\npm-cache\_prebuilds\https-github.com-level-leveldown-releases-download-v1.6.0-leveldown-v1.6.0-node-v48-win32-x64.tar.gz
prebuild-install http request GET https://github.com/level/leveldown/releases/download/v1.6.0/leveldown-v1.6.0-node-v48-win32-x64.tar.gz
prebuild-install WARN install unable to verify the first certificate

C:\Users\HP\AppData\Roaming\npm\node_modules\levelmeup\node_modules\leveldown>if not defined npm_config_node_gyp (node "C:\Users\HP\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at Object.failNoPython (C:\Users\HP\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:482:19)
gyp ERR! stack     at Object.<anonymous> (C:\Users\HP\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Users\HP\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\HP\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\HP\AppData\Roaming\npm\node_modules\levelmeup\node_modules\leveldown
gyp ERR! node -v v6.10.2
gyp ERR! node-gyp -v v3.6.0
gyp ERR! not ok
C:\Users\HP\AppData\Roaming\npm
`-- (empty)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! leveldown@1.6.0 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the leveldown@1.6.0 install script 'prebuild-install || node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the leveldown package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     prebuild-install || node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs leveldown
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls leveldown
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\HP\AppData\Roaming\npm-cache\_logs\2017-04-30T19_22_02_836Z-debug.log

**Comment by ralphtheninja** [comment]
This should work now since there are prebuilt binaries for leveldown on windows. Please re-open if this is not the case.
