### ISSUE TITLE
Wrong problem description for Exercise 12

### ISSUE THREAD

**Issue by DCrow** [workshopper/levelmeup#118]
> Fetch the value from the data store with the key multilevelmeup and print
  it to the console.

Description for exercise 12 asks to print value to the console, but it actually requires it to be passed into callback function.
Also nothing is said about IN parameters for this exercise module.

**Comment by martinheidegger** [comment]
Fixed in https://github.com/workshopper/levelmeup/commit/ccce5cff144f90904670f086a170e3522a59d7b6 follow https://github.com/workshopper/org/issues/35 to get updated about the deployment of v1.0.1
