### ISSUE TITLE
npm WARN deprecated object-keys@0.2.0: Please update to the latest object-keys

### ISSUE THREAD

**Issue by thehme** [workshopper/levelmeup#36]
Not sure if you are aware of this, but I installed this using the following command:

npm install -g levelmeup

and what prints is something about a deprecated object-keys:

    npm WARN deprecated object-keys@0.2.0: Please update to the latest object-keys
    > leveldown@0.10.2 install    /usr/local/lib/node_modules/levelmeup/node_modules/level/node_modules/leveldown
    > node-gyp rebuild

      CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/db/builder.o
      CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/db/db_impl.o
      CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/db/db_iter.o
      CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/db/filename.o
      CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/db/dbformat.o
      CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/db/log_reader.o
      CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/db/log_writer.o
      CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/db/memtable.o
      CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/db/repair.o
      CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/db/table_cache.o
      CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/db/version_edit.o
      CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/db/version_set.o
      CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/db/write_batch.o
      CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/helpers/memenv/memenv.o
      CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/table/block.o
      CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/table/block_builder.o
      CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/table/filter_block.o
      CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/table/format.o
      CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/table/iterator.o
      CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/table/merger.o
      CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/table/table.o
      CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/table/table_builder.o
      CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/table/two_level_iterator.o
      CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/util/arena.o
      CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/util/bloom.o
      CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/util/cache.o
      CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/util/coding.o
      CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/util/comparator.o
      CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/util/crc32c.o
      CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/util/env.o
      CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/util/filter_policy.o
      CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/util/hash.o
      CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/util/logging.o
      CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/util/options.o
      CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/util/status.o
      CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/port/port_posix.o
      CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.14.0/util/env_posix.o
      LIBTOOL-STATIC Release/leveldb.a
      CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.1/snappy-sinksource.o
      CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.1/snappy-stubs-internal.o
      CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.1/snappy.o
      LIBTOOL-STATIC Release/snappy.a
      CXX(target) Release/obj.target/leveldown/src/batch.o
      CXX(target) Release/obj.target/leveldown/src/batch_async.o
      CXX(target) Release/obj.target/leveldown/src/database.o
      CXX(target) Release/obj.target/leveldown/src/database_async.o
      CXX(target) Release/obj.target/leveldown/src/iterator.o
      CXX(target) Release/obj.target/leveldown/src/iterator_async.o
      CXX(target) Release/obj.target/leveldown/src/leveldown.o
      CXX(target) Release/obj.target/leveldown/src/leveldown_async.o
      SOLINK_MODULE(target) Release/leveldown.node
      SOLINK_MODULE(target) Release/leveldown.node: Finished
    /usr/local/bin/levelmeup -> /usr/local/lib/node_modules/levelmeup/levelmeup.js levelmeup@0.1.10 /usr/local/lib/node_modules/levelmeup
    ├── after@0.8.1
    ├── echomunge@0.2.0
    ├── rimraf@2.2.8
    ├── readable-stream@1.0.33 (isarray@0.0.1, inherits@2.0.1, string_decoder@0.10.31, core-util-is@1.0.1)
    ├── through2@0.2.3 (readable-stream@1.1.13, xtend@2.1.2)
    ├── through2-map@1.1.0 (through2@0.1.0)
    ├── workshopper@0.3.3 (map-async@0.1.1, tuple-stream@0.0.2, split@0.2.10, through@2.3.6,, mkdirp@0.3.5, xtend@2.1.2, colors-tmpl@0.1.1, terminal-menu@0.1.0, optimist@0.6.1, pygmentize-bundled@2.1.1)
    ├── multilevel@5.5.0 (duplexer@0.0.4, stream-combiner@0.0.4, level-manifest@1.1.1, tmp-stream@0.2.3, rpc-stream@1.0.5, mux-demux@3.7.9)
    ├── level-sublevel@6.2.2 (ltgt@1.0.2, levelup@0.18.6, pull-stream@2.21.0)
    └── level@0.18.0 (level-packager@0.18.0, leveldown@0.10.2)

Thank you

**Comment by ralphtheninja** [comment]
It's due to an outdated version of `through2-map`

![object-keys](https://cloud.githubusercontent.com/assets/308049/9779392/567c862e-577b-11e5-99c3-2a77f72202ef.png)

**Comment by ralphtheninja** [comment]
I'm closing this in favor of https://github.com/workshopper/levelmeup/issues/47

**Comment by knseir** [comment]
@ralphtheninja , I don't understand, How do I fix this ?
I have the same problem, how can I update through2-map ?

**Comment by animanga** [comment]
I haved same problem with node latest version used node 8 and then i see problems with npm install and more like if you try install package another it remowes more :) so my solution was downgrade to node LTS 6 version :) and ionic 2 with npm working fine

**Comment by saber13812002** [comment]
how can i use node 6 and node 8 beside.. how can upgrade these projects with lagacy depricated lib?
