### ISSUE TITLE
Possible move to the "workshopper" or "level" org

### ISSUE THREAD

**Issue by rvagg** [workshopper/levelmeup#40]
See https://github.com/rvagg/learnyounode/issues/254 for context.

I'm moving learnyounode and my workshopper-\* repos over to the workshopper org for better governance and collaboration and to help remove myself as the primary bottleneck to progress.

I'm unsure about whether to move this module or not since it's not in the same boat as learnyounode and there is also the "level" org that it could move to. This project hasn't been as active as I'd like and it hasn't been upgraded to the new workshopper and I don't know if there's even anyone else on here who's passionate enough about this project to put more effort in to it.

Any thoughts from collaborators?

**Comment by ralphtheninja** [comment]
I was writing down some thoughts today and one of them was about this project. We should definitely put some TLC into it.

Where to put it? It doesn't really matter to me, but I think it would be cool if it belonged to the workshopper org.
