### ISSUE TITLE
Get Your Level On! fails at verifying

### ISSUE THREAD

**Issue by carloscarvallo** [workshopper/levelmeup#60]
I tested with my created data and it worked
but with the levelmeup it fails at verifying
this project its abandoned?
I tested with node v4.2.1 and its not worked (some module  version mismatch)
and with node v0.12.0 I got this err
![image](http://i.imgur.com/7ieG07p.png)

**Comment by martinheidegger** [comment]
This problem should be solved with the recently release 1.0.0 issue. Would you mind to retest it?

**Comment by martinheidegger** [comment]
Assuming its fixed.
