### ISSUE TITLE
npm ERR! fetch failed https://codeload.github.com/dominictarr/node-levelup/tar.gz/inject 

### ISSUE THREAD

**Issue by shotlom** [workshopper/levelmeup#62]
npm ERR! fetch failed https://codeload.github.com/dominictarr/node-levelup/tar.gz/inject
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404

node v5.6.0

**Comment by purepennons** [comment]
Has same problem.

**Comment by ecwyne** [comment]
Same here
npm --version 3.3.6
node --version v5.0.0
osx 10.11.4

**Comment by justin-calleja** [comment]
Same with node:
node v0.12.2, npm v2.7.4
node v5.0.0, npm v3.3.6
node v6.3.1, npm v3.10.3

**Comment by martinheidegger** [comment]
Node v5 is not maintained anymore and thus not supported anymore (an requires on-demand builds). The other versions work on my machine. Would you mind to recheck?

**Comment by martinheidegger** [comment]
Assuming it fixed.
