### ISSUE TITLE
Start/End options for readStreams are legacy ranges

### ISSUE THREAD

**Issue by xaviervalarino** [workshopper/levelmeup#80]
`start` and `end` options are labelled as legacy ranges, suggesting the use of `lte` (less than or equal) and `gte` (greater than or equal) instead. 

From the [LevelUp README](https://github.com/Level/levelup#dbcreatereadstreamoptions):

> Additionally, you can supply an options object as the first parameter to createReadStream() with the following options:
> 
> 'gt' (greater than), 'gte' (greater than or equal) define the lower bound of the range to be streamed. Only records where the key is greater than (or equal to) this option will be included in the range. When reverse=true the order will be reversed, but the records streamed will be the same.
> 
> 'lt' (less than), 'lte' (less than or equal) define the higher bound of the range to be streamed. Only key/value pairs where the key is less than (or equal to) this option will be included in the range. When reverse=true the order will be reversed, but the records streamed will be the same.
> 
> **'start', 'end' legacy ranges - instead use 'gte', 'lte'**

Exercises _@horse_js Tweets_, _Keywise_, and _Short Scrabble Words_ all reference using `start` and `end`. Is it worthwhile to update these exercises? I can create a PR.

**Comment by martinheidegger** [comment]
Fixed in https://github.com/workshopper/levelmeup/pull/39 thank you for pointing this out!
