### ISSUE TITLE
Deploy latest version

### ISSUE THREAD

**Issue by martinheidegger** [workshopper/levelmeup#91]
@workshopper/deploy It would be cool if we could publish the latest version of levelmeup, would you mind giving it a look?

**Comment by julianduque** [comment]
only @rvagg @juliangruber and @ralphtheninja have access to deploy

**Comment by ralphtheninja** [comment]
1.0.0

**Comment by ralphtheninja** [comment]
@martinheidegger What's your nick on npm? I can give you access if you like.

**Comment by martinheidegger** [comment]
@ralphtheninja It is good that we have a dedicated deployment team (this way a little bit of review is happening). It would be good if @julianduque could get access though (he is on the deployment team)

**Comment by martinheidegger** [comment]
Oh! And thank you for deploying :tada:

**Comment by ralphtheninja** [comment]
```
lms@ux301 ~/src/workshopper/levelmeup (master)
$ npm owner ls
julianduque <julianduquej@gmail.com>
juliangruber <julian@juliangruber.com>
ralphtheninja <ralphtheninja@riseup.net>
rvagg <rod@vagg.org>
```

**Comment by julianduque** [comment]
Thanks @ralphtheninja !
