### ISSUE TITLE
Basics get

### ISSUE THREAD

**Issue by emilefyon** [workshopper/levelmeup#96]
```
module.exports = function (databaseDir, callback) {  
       var result = []  
       // your code...  
       result.push()  
       // more code...  
       callback(result)  
     } 
```

Should be :

```
module.exports = function (databaseDir, callback) {  
       var result = []  
       // your code...  
       result.push()  
       // more code...  
       callback(err, result)  
     } 
```

For sake of clarity, I would also add 

> The store will contain up to 10 entries with keys in the form:  
>     key[X]  
>  Where '[X]' is an integer between 0 and 100.  

> The store will contain up to 10 entries with keys in the form:  
>     key[X]  
>  Where '[X]' is an integer between 0 and 100.  Keys are key1, key2, key3, etc.

Took me a loooooong time to get it and I had to review solutions from past version...

But thanks for the work ! Interesting ;)

**Comment by martinheidegger** [comment]
Fixed in https://github.com/workshopper/levelmeup/commit/00dc8c9c8e0be198fbe3c053ea730ce7cbfd40bf, follow https://github.com/workshopper/org/issues/35 to get updated about the deployment of v1.0.1
